.travis.yml, addon-test-support/helpers.js, testem.js, tests/integration/key-event-test.js
- When running tests window may not be in focus, so manually fire focus, otherwise use `el.focus()`
- Remove `$` (jQuery) from helper
- Use real browsers, not just PhantomJS
Fixes #3
=> Fire focus event even when window is not in focus

.gitignore, addon-test-support/helpers.js, addon-test-support/settings.js, ember-cli-build.js, package.json, tests/dummy/app/components/x-form.js, tests/dummy/app/styles/app.css, tests/dummy/app/templates/components/x-form.hbs, tests/integration/components/x-form-test.js, tests/integration/find-test.js, tests/test-helper.js, yarn.lock
Add find helper and use within test helpers
- Support same params as Ember's `find` helper, only not using `$`
- `find` helper uses `document.querySelectorAll` and when only one element is found, simple return that element; otherwise the `NodeList`
- Use app config/enviroment setting for `rootElement` (default is `#ember-testing`) - to query within the test DOM (vs all DOM including test runner HTML)
In order to support a `find` (DOM) query only inside the Ember application's DOM the consuming application's config is used. For now in `tests/test-helper.js` the default value for `#ember-testing` as the `rootElement` can be set per the app's config:
```js
import settings from 'ember-native-dom-helpers/test-support/settings';
import config from '../config/environment';
const { APP: { …
```
=> Add dummy app component/test, use rootElement to select

package.json
Try a build with the dependency for broccoli-concat removed. `yarn upgrade broccoli-concat` added under dependencies in package.json. Also, the yarn.lock ended up with two entries vs 3.2.0 and 3.2.2. Perhpas that is why the builds were failing without this dependency specified. Extra version removed from yarn.lock in 6a15aab
See https://github.com/broccolijs/broccoli-concat/issues/106#issuecomment-281811267
=> Remove broccoli-concat from package.json dependencies

addon-test-support/helpers.js, addon-test-support/settings.js, tests/integration/find-test.js
This addon is a way to start the gradual migration towards the future "testing unification" RFC setup. That RFC proposes only native DOM.
If a tests needs jQuery, it will be more explicit in the test code for the developer to wrap the find call, e.g. `jQuery(find('a'))`
=> Remove settings for optional jquery wrapped find result

addon-test-support/helpers.js, tests/integration/find-test.js
Originally the `find` helper returns an empty `NodeList` when the query has an empty result. Alternatively if the query has only a single result, instead of returning the `NodeList` with one `HTMLElement` the `find` helper returns the only result the `HTMLElement`. 
The check for an empty result is `find('.not-present').length === 0`. Since the helper is acting intuitive like either `document.querySelector` or `document.querySelectorAll` the return value should be similar. No result from `querySelector` is `null` and an no results from `querySelectorAll` is an empty `NodeList`. 
Checking for a `null` result when a query is made for one matching element makes sense. The find helper doesn't know that the result should be one or more based on the query. So returning an empty NodeList seems …
=> Find helper results null when query has empty result

addon-test-support/click.js, addon-test-support/fill-in.js, addon-test-support/find-all.js, addon-test-support/find.js, addon-test-support/focus.js, addon-test-support/helpers.js, addon-test-support/key-event.js, addon-test-support/trigger-event.js
It is shorter and if we rename the addon (which is likely) we don’t
need to do anything
=> Use relative imports inside same folder

README.md, addon-test-support/click.js, addon-test-support/fire-event.js, addon-test-support/helpers.js, addon-test-support/tap.js, firefox_config.js, testem.js, tests/integration/tap-test.js
It simulates the usual `tap` interaction on touch devices.
The logic of events is:
- Fire `touchstart`
- Fire `touchend`
- If none of the previous was defaultPrevented, fire a click secuence
(mousedown -> focus -> mouseup -> click)
=> Added `tap` helper

.eslintrc.js, .travis.yml, package.json, tests/dummy/app/components/x-form.js, tests/integration/click-test.js, tests/integration/components/x-form-test.js, tests/integration/fill-in-test.js, tests/integration/find-all-test.js, tests/integration/find-test.js, tests/integration/find-with-assert-test.js, tests/integration/key-event-test.js, tests/integration/tap-test.js, tests/integration/trigger-event-test.js, yarn.lock
`yarn upgrade` can help us catch errors due to updates in transitive dependencies
Also bower and phantom are installed using yarn instead of npm, because we can.
=> Add ember-suave and use yarn upgrade

README.md, addon-test-support/-private/get-element-with-assert.js, addon-test-support/-private/get-element.js, addon-test-support/click.js, addon-test-support/fill-in.js, addon-test-support/find-with-assert.js, addon-test-support/find.js, addon-test-support/key-event.js, addon-test-support/tap.js, addon-test-support/trigger-event.js, tests/integration/click-test.js, tests/integration/fill-in-test.js, tests/integration/key-event-test.js, tests/integration/tap-test.js, tests/integration/trigger-event-test.js
=> Interaction helpers also accept HTMLElements as first argument

.travis.yml, config/ember-try.js, ember-cli-build.js
* Add new ember-try scenario for `no-jquery`
* Add new scenario to `.travis.yml` (moving `default` and `no-jquery`
first in the matrix)
* Update `ember-cli-build.js` to properly disable using `jQuery` when
running under the correct ember-try scenario.
=> Add test harness support for testing without jQuery.

.travis.yml
latest is currently having issues, so downgrade to latest-esr for now.
Info from https://docs.travis-ci.com/user/firefox/.
=> Use latest-esr instead of latest.

addon-test-support/focus.js, testem.js, tests/integration/focus-test.js
FIxes #31
Well sort of fixes it. When we test in CI or during development without the browser focused `document.focus()` is not used, and there is no way to know what a test focused on last since there is no `document.activeElement`.
Adds new tests to show that when the browser window has focus a blur event is fired naturally as a result of a call to `document.focus()` in the focus helper.
Remove use of PhantomJS in CI, no need only has issues with focus/blur behaviors which aren't helpful.
=> Blur before focus (when document has focus)

.eslintrc.js, addon-test-support/helpers.js, addon-test-support/visit.js, addon-test-support/wait-until.js, package.json, tests/acceptance/usage-in-acceptance-test.js, tests/dummy/app/templates/dashboard-example-loading.hbs, tests/dummy/app/templates/dashboard-example.hbs, tests/dummy/app/templates/signup-example.hbs, tests/dummy/config/targets.js, tests/integration/visit.js, tests/integration/wait-until-test.js, yarn.lock
This PR is opened with a failing test that demonstrates the tentative API
for acceptance test, including an example of asserting transient loading
substates.
=> Acceptance test tentative API

README.md, addon-test-support/index.js, addon-test-support/test-support/helpers.js, index.js, package.json, tests/acceptance/usage-in-acceptance-test.js, tests/integration/click-test.js, tests/integration/components/x-form-test.js, tests/integration/fill-in-test.js, tests/integration/find-all-test.js, tests/integration/find-test.js, tests/integration/find-with-assert-test.js, tests/integration/focus-test.js, tests/integration/key-event-test.js, tests/integration/tap-test.js, tests/integration/trigger-event-test.js, tests/integration/visit.js, tests/integration/wait-until-test.js, tests/test-helper.js
Leads to nicer imports:
```js
// new 
import { click, fillIn } from 'ember-native-dom-helpers';
// old 
import { click, fillIn } from 'ember-native-dom-helpers/test-support/helpers';
```
The  `ember-native-dom-helpers/test-support/helpers` module still functions properly, it just emits a deprecation that that module path is deprecated.
=> Implement treeForAddonTestSupport to override shifting behavior.

addon-test-support/focus.js, tests/integration/focus-test.js
@pixelhandler You thought about this. I actually found a situation where it's needed, so I made it public (and enhance it to accept either a selector or a HTMLElement)
=> Make `focus` helper public

ember-cli-build.js, package.json, tests/dummy/config/targets.js
Relates to https://github.com/cibernox/ember-native-dom-helpers/issues/52
~~Fancy features are used in this repo, so requires node 6+~~
EDIT: using strict mode if in node 4
=> Fixes strict mode & running in node 4

addon-test-support/blur.js, tests/integration/blur-test.js
Alongside the focus event, I've added blur event as well. Blur seems to have similar issues when the browser is not focused, tests will fail. Triggering native event helps, event though I am not exactly sure, that it will result in 'exactly' the same behavior.
What you guys think?
=> Blur event

README.md, addon-test-support/-private/is-focusable.js, addon-test-support/blur.js, addon-test-support/fire-event.js, addon-test-support/focus.js, addon-test-support/key-event.js
When the window is focused and unfocused, event triggering works differently. 
1. When the window is unfocused, `el.focus()` is only setting document.activeElement = el;
2. When the window is focused, `el.focus` will set document.activeElement and will also trigger focus event.
This PR will simulate this behavior and help to be consistent between focused and unfocused window.
=> Improve focus/blur/keyboard events handling

package.json, yarn.lock
I intend to use assertions to guide users towards mode idiomatic
usages.
E.g.
- `triggerEvent(selector, 'blur')` VS `blur(selector)`. I think we should settle
on only one.
- `triggerEvent(selector, 'focusin/out')`. This is an artificial event that is
a consequence of a focus/blur event, so I think that it should be disallowed
with a nice warning message that tells the user to use focus/blur instead.
=> Update ember-cli-babel to 6.1 to have access to debug utilities

addon-test-support/click.js, tests/integration/click-test.js
This is so to behave like the helper provided by ember
=> Allow to pass a context HTMLElement to `click`

addon-test-support/find-all.js, tests/integration/find-all-test.js
Resolves #77 
/cc @cibernox @rwjblue
=> findAll(): Return JS array instead of NodeList

addon-test-support/fire-event.js, addon-test-support/index.js, addon-test-support/select-files.js, tests/integration/select-files-test.js
In order to select files, you need to assign the file to the files property on the event's target. This is a readonly property, so need to use defineProperty in order to overwrite it.
Could do this to currentTarget as well if it's felt that would be beneficial. originalTarget and even explicitOriginalTarget should be left alone I feel for the sake of the test helper.
Closes #82
=> Added a 'triggerFileSelect' method to test selecting of files

README.md, addon-test-support/find-all.js, tests/integration/find-all-test.js
Before it could only be an HTMLElement
=> Allow the `context` received by findAll to be a CSS selector

README.md
As previously written, it was implied that native events being very verbose and having browser incompatibilities makes firing native events a no-brainer
=> [chore]: Fixing grammar in README

addon-test-support/wait-until.js, tests/integration/wait-until-test.js
Before it would call the callback at least twice, first on the initial `waitUntil` call, and at least another time within the `tick` function, even if it returned a truthy value immediately and the returned Promise was already resolved.
For something like this...
```
await waitUntil(() => find('.foo').classList.contains('.bar'));
```
this could lead to an exception, when the second (superfluous) call was made after the test has finished already, so `find('.foo')` returns `null`.
=> Fix waitUntil to call callback just once if it immediately returns truthy value

addon-test-support/find-all.js, tests/integration/find-all-test.js
Instead of passing two strings, the user can just as well join them
=> There is no point in receiving a string as context.

CHANGELOG.md, addon-test-support/-private/is-focusable.js, tests/integration/focus-test.js
`<div tabindex="0">` should be focusable.
/cc @xcambar
=> [BUGFIX] Allow to focus non-focusable-by-default elements if they have tabindex

addon-test-support/find-all.js, tests/integration/find-all-test.js
If an svg was passed to as the second argument to findAll it was ignored because it's not an instance of HTMLElement.
=> findAll can accept SVG as second argument

addon-test-support/settings.js, tests/integration/find-test.js, tests/test-helper.js
Fixes #63
See https://github.com/emberjs/ember-test-helpers/blob/1e505a9de65b6a6352abc16698df7e3eb816c151/addon-test-support/%40ember/test-helpers/setup-rendering-context.js#L152
Hopefully this will not affect too many users, but might still be a breaking change for some, so probably would require a minor version bump?
=> Fixes rootElement to match that of this.$()[0]

addon-test-support/settings.js, tests/integration/find-test.js, tests/test-helper.js
This reverts commit 6300642eb033c12631fe83b6b22c70594f6dff4c.
=> Revert "Fixes rootElement to match that of this.$()[0] (#121)"

addon-test-support/-private/is-content-editable.js, addon-test-support/-private/is-focusable.js, addon-test-support/fill-in.js
Reference: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/isContentEditable
Closes #133
=> Use built-in `Element.isContentEditable` property

addon-test-support/click.js, addon-test-support/current-path.js, addon-test-support/current-route-name.js, addon-test-support/current-url.js, addon-test-support/fill-in.js, addon-test-support/key-event.js, addon-test-support/visit.js, addon-test-support/wait-until.js, testem.js
@Turbo87 Any idea on how to add conditional deprecations only if the user has a modern versions of ember-cli-qunit/mocha?
Perhaps it's not that bad that we display it unconditionally. AFAIK there is no breaking change in those new versions of qunit and using the new testing API is completely optional, so it might help with adoption.
=> Add deprecations for methods that are now in @ember/test-helpers
